using Microsoft.EntityFrameworkCore;
using POSApp.Data.Models;
namespace POSApp.Data.Services;
public class PurchaseInvoiceService
{
 public List<PurchaseInvoice> GetAll(User? actor=null){using var db=new LocalDbContext();var q=db.PurchaseInvoices.Include(x=>x.Items).Where(x=>!x.IsDeleted);if(actor!=null&&!PosAuthorizationService.IsAdmin(actor))q=q.Where(x=>x.BranchId==(actor.PrimaryBranchId??1));return q.OrderByDescending(x=>x.PurchaseDate).ToList();}
 public PurchaseInvoice? GetByGuid(Guid guid){using var db=new LocalDbContext();return db.PurchaseInvoices.Include(x=>x.Items).FirstOrDefault(x=>x.Guid==guid&&!x.IsDeleted);}
 public PurchaseInvoice Create(PurchaseInvoice purchaseInvoice,string deviceId,User? actor=null){if(actor!=null)PosAuthorizationService.Require(PosAuthorizationService.CanManagePurchases(actor),"Purchase management requires Manager/Admin permission.");using var db=new LocalDbContext();using var tx=db.Database.BeginTransaction();purchaseInvoice.BranchId=actor?.PrimaryBranchId??purchaseInvoice.BranchId;if(purchaseInvoice.BranchId<=0)purchaseInvoice.BranchId=1;purchaseInvoice.PurchaseNumber=GeneratePurchaseNumber(db,purchaseInvoice.BranchId);purchaseInvoice.UpdatedAtUtc=DateTime.UtcNow;purchaseInvoice.IsSynced=false;db.PurchaseInvoices.Add(purchaseInvoice);db.SaveChanges();foreach(var item in purchaseInvoice.Items){item.Guid=item.Guid==Guid.Empty?Guid.NewGuid():item.Guid;item.IsSynced=false;item.UpdatedAtUtc=DateTime.UtcNow;var product=db.Products.FirstOrDefault(p=>p.Guid==item.ProductGuid&&p.BranchId==purchaseInvoice.BranchId);if(product!=null){product.Quantity+=(int)item.Quantity;product.PurchasePrice=item.CostPrice;product.IsSynced=false;product.UpdatedAtUtc=DateTime.UtcNow;db.InventoryTransactions.Add(new InventoryTransaction{ProductGuid=product.Guid,BranchId=purchaseInvoice.BranchId,QuantityChange=item.Quantity,QuantityAfter=product.Quantity,Type="Purchase",Reference=purchaseInvoice.PurchaseNumber,CreatedBy=actor?.Username});}}db.SaveChanges();tx.Commit();return purchaseInvoice;}
 public PurchaseInvoice Update(PurchaseInvoice purchaseInvoice){using var db=new LocalDbContext();purchaseInvoice.UpdatedAtUtc=DateTime.UtcNow;purchaseInvoice.IsSynced=false;db.PurchaseInvoices.Update(purchaseInvoice);db.SaveChanges();return purchaseInvoice;}
 public void Delete(int id,User? actor=null){if(actor!=null)PosAuthorizationService.Require(PosAuthorizationService.CanManagePurchases(actor));using var db=new LocalDbContext();var p=db.PurchaseInvoices.Find(id);if(p==null)return;p.IsDeleted=true;p.IsSynced=false;p.UpdatedAtUtc=DateTime.UtcNow;db.SaveChanges();}
 private string GeneratePurchaseNumber(LocalDbContext db,int branchId){var prefix=$"PUR-{DateTime.Now:yyyyMMdd}-{branchId}-";var n=db.PurchaseInvoices.Count(x=>x.PurchaseNumber.StartsWith(prefix))+1;return $"{prefix}{n:D4}";}
}
